### ISSUE TITLE
Upgrade to pfUnit >=4.0

### ISSUE THREAD

**Issue by Mikolaj-A-Kowalski** [CambridgeNuclear/SCONE#10]
I have run into a problem where our gold old pfUnit python preprocessor fails with Python 3.10 [But should fail for any version >=3.8] 
The reason seems to be the fact that it cannot find the `iterable` in `collections` module, which is due to the fact that it has been deprecated. As the result we have no choice but to update to pfUnit 4.0. Due to the requirements of the latter it will mean the definite end of support for the older gfortran versions. Hopefully we will be able to preserve 8. At worst we will need to switch to 9. 

I will start looking into that and try to keep this thread updated.

**Comment by ChasingNeutrons** [comment]
Resolved by #70
