### ISSUE TITLE
Precomputing the majorant + unionised grids with S(alpha,beta)

### ISSUE THREAD

**Issue by ChasingNeutrons** [CambridgeNuclear/SCONE#28]
At the moment, by default SCONE does not precompute the majorant when using delta tracking. This will hamstring delta tracking performance in problems with many materials/nuclides. One way of doing this is to use unionised grids (through using aceNeutronDatabaseUni). This has two problems: for problems with lots of nuclides present this will also become inefficient and it also currently does not work when S(alpha,beta) is turned on.

I suppose the ideal fix would be having a nice option for general majorant precomputation. I'd like to try and work on this when I get some time but I'm happy for anyone else to dive in.

**Comment by valeriaRaffuzzi** [comment]
Solved with PR #106.
