### ISSUE TITLE
Updating inputs

### ISSUE THREAD

**Issue by ChasingNeutrons** [CambridgeNuclear/SCONE#29]
Some of the example inputs we have in the repository by default are showing their age a bit. 

First, it would be good to have some which are perhaps a bit more commented and more standard rather than the mix at the moment.

Second, in the benchmarks, the S(alpha,beta) format is an older style that we used to have so these should be updated.

Finally, the inputs should have their aceLibrary variable converted to the environmental variable $SCONE_ACE (rather than pointing to somewhere on my/Mikolaj's/Valeria's computer!

**Comment by Mikolaj-A-Kowalski** [comment]
Resolved with #51
