### ISSUE TITLE
Small fix needed in input file reading

### ISSUE THREAD

**Issue by valeriaRaffuzzi** [CambridgeNuclear/SCONE#6]
When in the input file one writes, for example, for an energy boundary, 1E-11 rather than 1.0E-11, SCONE reads 1E-111. We should either fix this or at least have a warning when energy values are unreasonable.

**Comment by ChasingNeutrons** [comment]
Oh my gosh! Any idea what's causing it in the parser? I wonder how this has affected results accuracy when inputting different nuclide densities and MG XSs...

**Comment by valeriaRaffuzzi** [comment]
No, I don't know what causes it yet. To me it happened several times when I was including an energyMap in the tallies, but surely it might be an issue when reading xss too.

**Comment by Mikolaj-A-Kowalski** [comment]
I think my confusion about Fortran formats is to blame  
https://github.com/CambridgeNuclear/SCONE/blob/9f0adb663f5b25d450159e620d4856b88b1fdd54/DataStructures/dictParser_func.f90#L644
I think if it is changed to 
```Fortran
fmt = "(ES"//numToChar(pathLen)//".0)"
```
It should read correctly.
I will have a look into the standard and try to figure out why it behaved the way it did. 

We also need to add a test to catch this case and make sure things are correct.
