### ISSUE TITLE
Unionised grid DBs yay or nay?

### ISSUE THREAD

**Issue by valeriaRaffuzzi** [CambridgeNuclear/SCONE#64]
I propose getting rid of the unionised grid databases. 

This is because:
- a lot of physics is not implemented there (Sab and urr, and soon dbrc), because it would keep some not very elegant book-keeping that would be ugly and confusing right now
- probably having a different database class is not the nicest way to incorporate unionised grids
- it's annoying to maintain

I think a nice alternative would be do remove them (they are stored in some past version of the repository anyway), and in the future implement hash tables and make them the default method. 

Opinions? NOTE that I need answers before I can merge DBRC.

**Comment by Mikolaj-A-Kowalski** [comment]
I would say go for it. 
Especially true is the 2nd point. We just need to figure out a better design to support different interpolation methods. 
Basically nuclear data needs some kind of refactoring.

**Comment by valeriaRaffuzzi** [comment]
> I agree with all of these points. The only problem is that unionised grids occur quite naturally in constructing a majorant, which will be necessary to achieve a reasonable performance for large/burned delta tracking problems. Is there any nice way to preserve the unionised grid or a part of it for the majorant?

I think the best way to do this now is to take a step back and remove those databases. In the future, we can steal the useful functions and use them to build the majorant within the aceNeutronDatabase (that would require a bit of work to stitch things together but it shouldn't be too hard). We can maybe open a new issue about this when this one is closed.

**Comment by valeriaRaffuzzi** [comment]
Ok in this case, since everyone agrees, I will go on and do it!
