### ISSUE TITLE
Material colourmaps

### ISSUE THREAD

**Issue by Mikolaj-A-Kowalski** [CambridgeNuclear/SCONE#80]
It is well know by this point that the Knuth hash maps index 1 (usually water or other coolant in the reactor) into a very unappealing shade of brown in 24-bit colour space. Perhaps to increase the visual appeal of the plots we should introduce a way of specifying a colormaps. 

The main question is if the user defined 24bit colours should be defined in the `materials` dictionary or in the separate dictionary in the bmp visualisation definition. Personally I am more inclined to the latter option.

**Comment by valeriaRaffuzzi** [comment]
Great call!!! I hate that color.

From a user perspective I think it would be more intuitive to just add an optional 'color (a b c)' entry to the material definition, that is just ignored if the viz bmp is not included. But I am not too familiar with the graph, so it could be just more convenient to implement it in the bmp directly.

**Comment by Mikolaj-A-Kowalski** [comment]
My dislike for the definition in the `material` is that this is entry which is likely to be used by bmp visualisation only! 
This is why I am reluctant to put colours there... but perhaps it is just my paranoia.

**Comment by valeriaRaffuzzi** [comment]
Yes I can see that it would be an extra property to be carried around. I do think it would be more user friendly to have it in the material, but I don't have a strong opinion on this and it shouldn't make a massive difference either way! So I don't mind in the end.
